from frappe.model.document import Document
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


class MetaMarketingKPI(Document):
    pass


def ensure_meta_marketing_kpi_custom_fields():
    fields = [
        {"fieldname": "device_mobile_app", "label": "Device Mobile App", "fieldtype": "Int"},
        {"fieldname": "device_mobile_web", "label": "Device Mobile Web", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_total_messaging_connection", "label": "Act Onsite Conversion Total Messaging Connection", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_messaging_block", "label": "Act Onsite Conversion Messaging Block", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_post_unlike", "label": "Act Onsite Conversion Post Unlike", "fieldtype": "Int"},
        {"fieldname": "act_like", "label": "Act Like", "fieldtype": "Int"},
        {"fieldname": "act_post_interaction_gross", "label": "Act Post Interaction Gross", "fieldtype": "Int"},
        {"fieldname": "act_post_interaction_net", "label": "Act Post Interaction Net", "fieldtype": "Int"},
        {"fieldname": "act_post", "label": "Act Post", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_post_save", "label": "Act Onsite Conversion Post Save", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_post_net_comment", "label": "Act Onsite Conversion Post Net Comment", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_post_net_save", "label": "Act Onsite Conversion Post Net Save", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_post_net_like", "label": "Act Onsite Conversion Post Net Like", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_messaging_conversation_started_7d", "label": "Act Onsite Conversion Messaging Conversation Started 7D", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_messaging_conversation_replied_7d", "label": "Act Onsite Conversion Messaging Conversation Replied 7D", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_messaging_user_depth_2_message_send", "label": "Act Onsite Conversion Messaging User Depth 2 Message Send", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_messaging_user_depth_3_message_send", "label": "Act Onsite Conversion Messaging User Depth 3 Message Send", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_messaging_user_depth_5_message_send", "label": "Act Onsite Conversion Messaging User Depth 5 Message Send", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_lead", "label": "Act Onsite Conversion Lead", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_lead_grouped", "label": "Act Onsite Conversion Lead Grouped", "fieldtype": "Int"},
        {"fieldname": "act_onsite_web_lead", "label": "Act Onsite Web Lead", "fieldtype": "Int"},
        {"fieldname": "act_offsite_complete_registration_add_meta_leads", "label": "Act Offsite Complete Registration Add Meta Leads", "fieldtype": "Int"},
        {"fieldname": "act_offsite_search_add_meta_leads", "label": "Act Offsite Search Add Meta Leads", "fieldtype": "Int"},
        {"fieldname": "act_offsite_content_view_add_meta_leads", "label": "Act Offsite Content View Add Meta Leads", "fieldtype": "Int"},
        {"fieldname": "act_lead_raw", "label": "Act Lead Raw", "fieldtype": "Int"},
        {"fieldname": "act_video_view_raw", "label": "Act Video View Raw", "fieldtype": "Int"},
        {"fieldname": "act_post_reaction_raw", "label": "Act Post Reaction Raw", "fieldtype": "Int"},
        {"fieldname": "act_onsite_conversion_post_unsave", "label": "Act Onsite Conversion Post Unsave", "fieldtype": "Int"},
        {"fieldname": "cost_video_view", "label": "Cost Video View", "fieldtype": "Currency"},
        {"fieldname": "cost_link_click", "label": "Cost Link Click", "fieldtype": "Currency"},
        {"fieldname": "cost_like", "label": "Cost Like", "fieldtype": "Currency"},
        {"fieldname": "cost_post_interaction_gross", "label": "Cost Post Interaction Gross", "fieldtype": "Currency"},
        {"fieldname": "cost_post_engagement", "label": "Cost Post Engagement", "fieldtype": "Currency"},
        {"fieldname": "cost_page_engagement", "label": "Cost Page Engagement", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_total_messaging_connection", "label": "Cost Onsite Conversion Total Messaging Connection", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_messaging_first_reply", "label": "Cost Onsite Conversion Messaging First Reply", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_messaging_conversation_started_7d", "label": "Cost Onsite Conversion Messaging Conversation Started 7D", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_messaging_conversation_replied_7d", "label": "Cost Onsite Conversion Messaging Conversation Replied 7D", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_messaging_user_depth_2_message_send", "label": "Cost Onsite Conversion Messaging User Depth 2 Message Send", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_messaging_user_depth_3_message_send", "label": "Cost Onsite Conversion Messaging User Depth 3 Message Send", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_messaging_user_depth_5_message_send", "label": "Cost Onsite Conversion Messaging User Depth 5 Message Send", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_lead", "label": "Cost Onsite Conversion Lead", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_conversion_lead_grouped", "label": "Cost Onsite Conversion Lead Grouped", "fieldtype": "Currency"},
        {"fieldname": "cost_onsite_web_lead", "label": "Cost Onsite Web Lead", "fieldtype": "Currency"},
        {"fieldname": "cost_offsite_submit_application_add_meta_leads", "label": "Cost Offsite Submit Application Add Meta Leads", "fieldtype": "Currency"},
        {"fieldname": "cost_offsite_search_add_meta_leads", "label": "Cost Offsite Search Add Meta Leads", "fieldtype": "Currency"},
        {"fieldname": "cost_offsite_complete_registration_add_meta_leads", "label": "Cost Offsite Complete Registration Add Meta Leads", "fieldtype": "Currency"},
        {"fieldname": "cost_offsite_content_view_add_meta_leads", "label": "Cost Offsite Content View Add Meta Leads", "fieldtype": "Currency"},
        {"fieldname": "cost_offsite_contact_website_add_meta_leads", "label": "Cost Offsite Contact Website Add Meta Leads", "fieldtype": "Currency"},
        {"fieldname": "cost_lead_raw", "label": "Cost Lead Raw", "fieldtype": "Currency"},
        {"fieldname": "unique_onsite_conversion_total_messaging_connection", "label": "Unique Onsite Conversion Total Messaging Connection", "fieldtype": "Int"},
        {"fieldname": "unique_onsite_conversion_messaging_first_reply", "label": "Unique Onsite Conversion Messaging First Reply", "fieldtype": "Int"},
        {"fieldname": "unique_onsite_conversion_returning_messaging_connection", "label": "Unique Onsite Conversion Returning Messaging Connection", "fieldtype": "Int"},
        {"fieldname": "unique_cost_onsite_conversion_total_messaging_connection", "label": "Unique Cost Onsite Conversion Total Messaging Connection", "fieldtype": "Currency"},
        {"fieldname": "unique_cost_link_click", "label": "Unique Cost Link Click", "fieldtype": "Currency"},
        {"fieldname": "unique_cost_onsite_conversion_returning_messaging_connection", "label": "Unique Cost Onsite Conversion Returning Messaging Connection", "fieldtype": "Currency"},
        {"fieldname": "unique_cost_onsite_conversion_messaging_first_reply", "label": "Unique Cost Onsite Conversion Messaging First Reply", "fieldtype": "Currency"},
        {"fieldname": "placement_facebook_facebook_reels", "label": "Placement Facebook Facebook Reels", "fieldtype": "Int"},
        {"fieldname": "placement_facebook_facebook_stories", "label": "Placement Facebook Facebook Stories", "fieldtype": "Int"},
        {"fieldname": "placement_facebook_feed", "label": "Placement Facebook Feed", "fieldtype": "Int"},
        {"fieldname": "placement_facebook_instream_video", "label": "Placement Facebook Instream Video", "fieldtype": "Int"},
        {"fieldname": "placement_facebook_search", "label": "Placement Facebook Search", "fieldtype": "Int"},
        {"fieldname": "placement_instagram_feed", "label": "Placement Instagram Feed", "fieldtype": "Int"},
        {"fieldname": "placement_instagram_instagram_explore", "label": "Placement Instagram Explore", "fieldtype": "Int"},
        {"fieldname": "placement_instagram_instagram_explore_grid_home", "label": "Placement Instagram Explore Grid Home", "fieldtype": "Int"},
        {"fieldname": "placement_instagram_instagram_reels", "label": "Placement Instagram Reels", "fieldtype": "Int"},
        {"fieldname": "placement_instagram_instagram_stories", "label": "Placement Instagram Stories", "fieldtype": "Int"},
        {"fieldname": "age_18_24_female", "label": "Age 18 24 Female", "fieldtype": "Int"},
        {"fieldname": "age_18_24_male", "label": "Age 18 24 Male", "fieldtype": "Int"},
        {"fieldname": "age_18_24_unknown", "label": "Age 18 24 Unknown", "fieldtype": "Int"},
        {"fieldname": "age_25_34_female", "label": "Age 25 34 Female", "fieldtype": "Int"},
        {"fieldname": "age_25_34_male", "label": "Age 25 34 Male", "fieldtype": "Int"},
        {"fieldname": "age_25_34_unknown", "label": "Age 25 34 Unknown", "fieldtype": "Int"},
        {"fieldname": "age_35_44_female", "label": "Age 35 44 Female", "fieldtype": "Int"},
        {"fieldname": "age_35_44_male", "label": "Age 35 44 Male", "fieldtype": "Int"},
        {"fieldname": "age_35_44_unknown", "label": "Age 35 44 Unknown", "fieldtype": "Int"},
        {"fieldname": "age_45_54_female", "label": "Age 45 54 Female", "fieldtype": "Int"},
        {"fieldname": "age_45_54_male", "label": "Age 45 54 Male", "fieldtype": "Int"},
        {"fieldname": "age_45_54_unknown", "label": "Age 45 54 Unknown", "fieldtype": "Int"},
        {"fieldname": "age_55_64_female", "label": "Age 55 64 Female", "fieldtype": "Int"},
        {"fieldname": "age_55_64_male", "label": "Age 55 64 Male", "fieldtype": "Int"},
        {"fieldname": "age_55_64_unknown", "label": "Age 55 64 Unknown", "fieldtype": "Int"},
        {"fieldname": "age_65_plus_female", "label": "Age 65 Plus Female", "fieldtype": "Int"},
        {"fieldname": "age_65_plus_male", "label": "Age 65 Plus Male", "fieldtype": "Int"},
        {"fieldname": "age_65_plus_unknown", "label": "Age 65 Plus Unknown", "fieldtype": "Int"},
    ]

    for field in fields:
        field["insert_after"] = "creative_type"

    create_custom_fields({"Meta Marketing KPI": fields}, update=True)
